version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry
      - asdf reshim
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -E 'duckdb pandas'

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

formats: all
