version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - duckdb
        - pandas
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

formats: all
