name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@v2.1.0
    - run: pip install poetry==1.2.2
    - run: nox --sessions test-3.9 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
